export interface Product {
    id: number;
    name: string;
    category: string;
    image: string;
    priceBefore: number;
    priceAfter: number;
    rating: number;
    new: boolean;
}

export const products: Product[] = [
    {
        id: 1,
        name: "Keitt Mangoes",
        category: "Mangoes",
        image: "/image/mango-fruit-collage.png",
        priceBefore: 78.0,
        priceAfter: 85.0,
        rating: 4.5,
        new: true,
    },

    {
        id: 5,
        name: "Minneola Tangelos",
        category: "Citrus",
        image: "/image/citrus.png",
        priceBefore: 65.0,
        priceAfter: 72.0,
        rating: 4.2,
        new: true,
    },

    {
        id: 8,
        name: "Yellow Barhi Dates",
        category: "Dates",
        image: "/image/dates.png",
        priceBefore: 70.0,
        priceAfter: 78.0,
        rating: 4.4,
        new: true,
    },

    {
        id: 11,
        name: "Pomegranate",
        category: "Pomegranates",
        image: "/image/pomegranates.png",
        priceBefore: 65.0,
        priceAfter: 72.0,
        rating: 4.2,
        new: true,
    },
    {
        id: 12,
        name: "Figs",
        category: "Figs",
        image: "/image/figs.png",
        priceBefore: 60.0,
        priceAfter: 68.0,
        rating: 4.3,
        new: true,
    },
    {
        id: 13,
        name: "Mirabelle Plums",
        category: "Plums",
        image: "/image/Mirabelle-Plums.png",
        priceBefore: 55.0,
        priceAfter: 62.0,
        rating: 4.1,
        new: true,
    },
    {
        id: 14,
        name: "Apples",
        category: "Apples",
        image: "/image/Gravenstein-Apples.png",
        priceBefore: 78.0,
        priceAfter: 85.0,
        rating: 4.0,
        new: true,
    },
    {
        id: 9,
        name: "Barhi Dates",
        category: "Dates",
        image: "/image/dates-shop.png",
        priceBefore: 68.0,
        priceAfter: 75.0,
        rating: 4.2,
        new: true,
    },
    {
        id: 20,
        name: "Santa Rosa Plums",
        category: "Plums",
        image: "/image/Santa-Rosa-Plums.png",
        priceBefore: 55.0,
        priceAfter: 62.0,
        rating: 4.1,
        new: true,
    },
    {
        id: 10,
        name: "Medjool Dates",
        category: "Dates",
        image: "/image/dates-shop.png",
        priceBefore: 80.0,
        priceAfter: 88.0,
        rating: 4.5,
        new: true,
    },
    {
        id: 15,
        name: "Thompson Grapes",
        category: "Grapes",
        image: "/image/Thompson-Grapes.png",
        priceBefore: 70.0,
        priceAfter: 78.0,
        rating: 4.4,
        new: true,
    },
    {
        id: 6,
        name: "Temple Oranges",
        category: "Citrus",
        image: "/image/citrus.png",
        priceBefore: 60.0,
        priceAfter: 68.0,
        rating: 4.3,
        new: true,
    },
    {
        id: 7,
        name: "Marsh Ruby Blush Grapefruit",
        category: "Citrus",
        image: "/image/citrus.png",
        priceBefore: 55.0,
        priceAfter: 62.0,
        rating: 4.1,
        new: true,
    },
    {
        id: 16,
        name: "Elberta Peaches",
        category: "Peaches",
        image: "/image/Elberta-Peaches.png",
        priceBefore: 75.0,
        priceAfter: 82.0,
        rating: 4.2,
        new: true,
    },
    {
        id: 2,
        name: "Desert Ruby Mangoes",
        category: "Mangoes",
        image: "/image/mango-fruit-collage.png",
        priceBefore: 80.0,
        priceAfter: 88.0,
        rating: 4.2,
        new: true,
    },
    {
        id: 3,
        name: "Valencia Pride Mangoes",
        category: "Mangoes",
        image: "/image/mango-fruit-collage.png",
        priceBefore: 75.0,
        priceAfter: 82.0,
        rating: 4.3,
        new: true,
    },
    {
        id: 4,
        name: "Golden Lady Mangoes",
        category: "Mangoes",
        image: "/image/mango-fruit-collage.png",
        priceBefore: 72.0,
        priceAfter: 79.0,
        rating: 4.1,
        new: true,
    },
    {
        id: 17,
        name: "Blenheim Apricots",
        category: "Apricots",
        image: "/image/Blenheim-Apricots.png",
        priceBefore: 68.0,
        priceAfter: 75.0,
        rating: 4.0,
        new: true,
    },
    {
        id: 18,
        name: "Nonpareil Almonds",
        category: "Almonds",
        image: "/image/Nonpareil-Almonds.png",
        priceBefore: 80.0,
        priceAfter: 88.0,
        rating: 4.5,
        new: true,
    },
    {
        id: 19,
        name: "Bartlett Pears",
        category: "Pears",
        image: "/image/Bartlett-Pears.png",
        priceBefore: 72.0,
        priceAfter: 79.0,
        rating: 4.3,
        new: true,
    },
];
